name: Deploy Natural Bathing to Hpanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Natural Bathing to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile
            which composer
            composer --version
            cd /home/u376682195/domains/naturalbathingpab.com/naturalbathing/
            git stash
            git pull origin develop
            composer update
            php artisan queue:restart
            php artisan cache:clear
            php artisan route:clear
            php artisan config:clear
            php artisan view:clear
            ln -s /home/u376682195/domains/naturalbathingpab.com/naturalbathing_admin/public/storage /home/u376682195/domains/naturalbathingpab.com/public_html
            chmod -R 775 storage
            chmod -R 775 public/storage
